import esbuild from 'esbuild'
import process from 'process'
import inlineWorkerPlugin from 'esbuild-plugin-inline-worker'
import fs from 'fs'
import path from 'path'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'
// Change this to your local Obsidian plugin path for development
const pluginDir = path.join(process.env.HOME || '', 'Desktop', 'obsidian-test', '.obsidian', 'plugins', 'mdfriday-sync');

// CSS rename plugin — renames main.css → styles.css (Obsidian requirement)
const cssRenamePlugin = {
	name: 'css-rename',
	setup(build) {
		build.onEnd((result) => {
			if (result && result.metafile) {
				const outputs = Object.keys(result.metafile.outputs).filter(file => file.endsWith('.css'));
				outputs.forEach(cssFile => {
					if (cssFile.includes('main.css')) {
						const cssPath = path.resolve(cssFile);
						const targetPath = prod
							? path.join(process.cwd(), 'styles.css')
							: path.join(pluginDir, 'styles.css');
						try {
							if (fs.existsSync(cssPath)) {
								fs.renameSync(cssPath, targetPath);
								console.log(`✓ Renamed CSS → ${targetPath}`);
							}
						} catch (e) {
							console.error(`Failed to rename CSS: ${e.message}`);
						}
					}
				});
			}
		});
	}
};

// External modules — provided by Obsidian / Electron (not bundled)
// NOTE: 'events' is intentionally NOT listed here so it is bundled via the
// Node.js polyfill (events@3.3.0) for PouchDB / SyncService on mobile.
// NOTE: 'path' is intentionally NOT listed here — we alias it to path-browserify
// so it works on both desktop and mobile.
const externals = [
        'obsidian',
        'electron',
        'crypto',
	'@codemirror/autocomplete', '@codemirror/closebrackets', '@codemirror/collab',
	'@codemirror/commands', '@codemirror/comment', '@codemirror/fold',
	'@codemirror/gutter', '@codemirror/highlight', '@codemirror/history',
	'@codemirror/language', '@codemirror/lint', '@codemirror/matchbrackets',
	'@codemirror/panel', '@codemirror/rangeset', '@codemirror/rectangular-selection',
	'@codemirror/search', '@codemirror/state', '@codemirror/stream-parser',
	'@codemirror/text', '@codemirror/tooltip', '@codemirror/view',
	'@lezer/common', '@lezer/highlight', '@lezer/lr',
        'fs', 'fs/promises', 'net', 'tls', 'stream', 'stream/promises',
        'http', 'https', 'util', 'os', 'process', 'url', 'worker_threads',
	'child_process', 'node:fs', 'node:fs/promises', 'node:path',
	'node:stream', 'node:process', 'node:url', 'node:worker_threads',
	'node:child_process',
];

const buildOptions = {
        banner: { js: banner },
        entryPoints: ['src/main.ts'],
        bundle: true,
        define: {
                'process.env.NODE_ENV': prod ? '"production"' : '"development"',
                global: 'window',
        },
        external: externals,
        alias: {
                // Replace Node's 'path' with browser-compatible path-browserify
                // This makes foundry/index.ts work on Obsidian mobile
                'path': 'path-browserify',
        },
        platform: 'browser',
	mainFields: ['browser', 'module', 'main'],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	metafile: true,
	plugins: [
		inlineWorkerPlugin({ external: externals, treeShaking: true }),
		cssRenamePlugin,
	],
	outfile: prod ? 'main.js' : path.join(pluginDir, 'main.js'),
};

buildOptions.loader = buildOptions.loader || {};
buildOptions.loader['.css'] = 'css';

if (prod) {
	esbuild.build(buildOptions)
		.then(() => console.log('✓ Build completed successfully'))
		.catch(() => process.exit(1));
} else {
	const context = await esbuild.context(buildOptions);
	await context.watch();
}

